# Generated by Django 3.2.13 on 2023-01-08 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsToGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, unique=True)),
                ('country', models.IntegerField(choices=[(1, 'PL'), (2, 'UK'), (3, 'USA')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuessedWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed', models.BooleanField()),
                ('guessed_attempt', models.IntegerField()),
                ('allowed_attempts', models.IntegerField()),
                ('game_date', models.DateTimeField()),
                ('guessed_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangman_app.wordstoguess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_letters', models.CharField(max_length=64)),
                ('current_attempt', models.IntegerField()),
                ('allowed_attempts', models.IntegerField()),
                ('game_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word_to_guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hangman_app.wordstoguess')),
            ],
        ),
    ]
