# Generated by Django 3.2.13 on 2023-03-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='finish_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='win_game',
            field=models.BooleanField(default=False),
        ),
    ]
