# Generated by Django 3.2.13 on 2023-03-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangman_app', '0002_auto_20230310_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_guess',
            field=models.CharField(default=False, max_length=64),
        ),
    ]
